export const premiumMockData = {
  addOns: [
    {
      add_id: 1,
      display_name: 'More Text',
      text_limit: 2000,
      us_price: 31.99,
      us_price_discount: 15.99,
    },
  ],
  subscriptions: {
    starter: {
      sub_id: 38,
      subscription_rank: 'Starter',
      monthly_point: 18000,
      month: 3,
      us_price: 31.47,
      point_per_thb: 90,
      product_id: null,
    },
    pro: {
      sub_id: 40,
      subscription_rank: 'Pro',
      monthly_point: 48000,
      month: 1,
      us_price: 39.99,
      point_per_thb: 120,
      product_id: null,
    },
    elite: {
      sub_id: 44,
      subscription_rank: 'Elite',
      monthly_point: 160000,
      month: 3,
      us_price: 299.99,
      point_per_thb: 160,
      product_id: null,
    },
    trialPlus: {
      sub_id: 52,
      subscription_rank: 'Trial',
      monthly_point: 35000,
      month: 1,
      us_price: 5.0,
      point_per_thb: 50,
      product_id: null,
    },
    yearlyStarter: {
      sub_id: 53,
      subscription_rank: 'Starter',
      monthly_point: 18000,
      month: 12,
      us_price: 130.0,
      point_per_thb: 100,
      product_id: null,
    },
    yearlyPro: {
      sub_id: 50,
      subscription_rank: 'Pro',
      monthly_point: 48000,
      month: 12,
      us_price: 350.0,
      point_per_thb: 140,
      product_id: null,
    },
    yearlyElite: {
      sub_id: 45,
      subscription_rank: 'Elite',
      monthly_point: 160000,
      month: 12,
      us_price: 1000.0,
      point_per_thb: 200,
      product_id: null,
    },
  },
};

