import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAngleDown } from "@fortawesome/free-solid-svg-icons";
import { faDownload } from "@fortawesome/free-solid-svg-icons";
import { faCirclePlay } from "@fortawesome/free-solid-svg-icons";


import "../App.css";

function HeroSection() {
    return (
        <section className="relative z-10 pt-16 pb-20 px-6">
            <div className="max-w-[1280px] mx-auto">
              <div className="grid lg:grid-cols-2 gap-12 lg:gap-20 items-center">
                {/* Left: Text */}
                <div className="flex flex-col gap-8 text-center lg:text-left">
                  <div className="flex flex-col gap-4">
                    <h1 className="text-[#0d0d1b] text-5xl md:text-6xl lg:text-[72px] font-black leading-[1.1] tracking-[-0.03em]">
                      CONVERT <span className="text-gradient">TEXT</span> <br />
                      TO <span className="text-gradient">SPEECH</span>
                    </h1>
                    <p className="text-gray-600 dark:text-gray-400 text-lg md:text-xl font-normal leading-relaxed max-w-lg mx-auto lg:mx-0">
                      Experience the most realistic AI voices. Convert text to
                      lifelike speech in seconds with our generative AI
                      technology.
                    </p>
                  </div>
                  <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                    <button className="h-14 px-8 rounded-full bg-button-gradient text-white text-base font-bold shadow-lg shadow-primary/30 hover:scale-105 transition-transform">
                      LET'S TRY FREE
                    </button>
                    <button className="h-14 px-8 rounded-full bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-[#0d0d1b] dark:text-white text-base font-bold hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors flex items-center gap-2 justify-center">
                      <FontAwesomeIcon icon={faCirclePlay} />
                      Watch Demo
                    </button>
                  </div>
                </div>

                {/* Right: Widget */}
                <div className="relative w-full max-w-lg mx-auto lg:max-w-none">
                  <div className="absolute -inset-4 bg-linear-to-r from-pink-300 via-purple-300 to-indigo-400 rounded-[2.5rem] blur-xl opacity-30 animate-pulse" />
                  <div className="relative bg-white  rounded-4xl p-6 shadow-2xl border border-white/50">
                    {/* Widget Header */}
                    <div className="flex items-center justify-between mb-4 border-b border-gray-100 dark:border-gray-800 pb-4">
                      <div className="flex items-center gap-3">
                        <div className="size-10 rounded-full bg-blue-100 flex items-center justify-center text-primary font-bold overflow-hidden border-2 border-primary">
                          <img
                            alt="AI Voice Avatar"
                            className="w-full h-full object-cover"
                            src="https://lh3.googleusercontent.com/aida-public/AB6AXuD190318vP5qbrGVlMgcKq-SrSD1ON3sqtkt-3lmF0ChifP2nyGudAEOQCEmct6XMxGCTzX12d4jg0Olh7au8MSvcPrXGkglMGcjpRuAroCnasfQPJSvS98i1MdLve6IlPtLWgPvFNOXfdQPderPi4RyfUq-CbsX6DzJbd856c9A27ljppYREPDvCQWW1P_7v4oY0-RzATYZRluP_18rcU0NsCnqzOTt1baEFz9ROuyRH1IlLk6EPrES1XDWYtSP8sP82w3d2ecOA"
                          />
                        </div>
                        <div>
                          <div className="text-sm font-bold dark:text-gray-500">
                            Jenny (US)
                          </div>
                          <div className="text-xs text-green-500 font-medium">
                            Pro Voice
                          </div>
                        </div>
                      </div>
                      <button className="text-xs font-bold text-gray-500 hover:text-primary flex items-center gap-1">
                        Change Voice
                        <span className="material-symbols-outlined text-sm">
                          <FontAwesomeIcon icon={faAngleDown} />
                        </span>
                      </button>
                    </div>

                    {/* Text Input */}
                    <div className="mb-4">
                      <textarea
                        className="w-full h-32 p-4 bg-gray-500  rounded-xl  resize-none focus:ring-2 focus:ring-primary/20 text-gray-700 dark:text-gray-300 text-sm leading-relaxed"
                        placeholder="Type something here to convert into speech..."
                        defaultValue="Hi! I am an AI voice generated by this amazing platform. I can read any text you type here with human-like intonation."
                      />
                      <div className="flex justify-between mt-2 text-xs text-gray-400 font-medium px-1">
                        <span>145 chars</span>
                        <span>Free Limit: 5000 chars</span>
                      </div>
                    </div>

                    {/* Controls */}
                    <div className="flex gap-3">
                      <button className="flex-1 h-12 bg-primary bg-blue-500 hover:bg-blue-700 text-white rounded-full font-bold text-sm shadow-lg shadow-blue-500/25 transition-all flex items-center justify-center gap-2 group">
                        Generate Audio
                      </button>
                      <button className="size-12 rounded-full  flex items-center justify-center bg-gray-500 hover:bg-gray-800 transition-colors">
                        <FontAwesomeIcon icon={faDownload} />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
    )
}

export default HeroSection ;